# These are supported sponsorship platforms

github: [Smart-rwl] # Replace with your GitHub username if different
patreon: # Add your username if you have a Patreon
ko_fi: # Add your username if you have a Ko-fi
custom: ["https://www.buymeacoffee.com/Smartrwl"]
