name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'documentation'
      - 'chore'

# 👈 ADD THIS SECTION
autolabeler:
  - label: 'feature'
    files:
      - 'reveal-seller.user.js'
  - label: 'documentation'
    files:
      - 'README.md'
      - 'CONTRIBUTING.md'
  - label: 'chore'
    files:
      - '.github/**/*'

template: |
  ## What’s Changed

  $CHANGES
